# Session 3 — Data Preprocessing (IPL Match Data)
---

## Question 1
**Download a small sample of IPL match data (CSV) with some missing values in player stats. Load it using pandas and print the number of missing values in each column.**

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# Creating a sample IPL Match Data CSV with missing values
# ============================================================

data = {
    'match_id':     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                     11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
                     21, 22, 23, 24, 25, 26, 27, 28, 29, 30],

    'player_name':  ['Virat Kohli', 'Rohit Sharma', 'MS Dhoni', 'Jasprit Bumrah', 'KL Rahul',
                     'Hardik Pandya', 'Ravindra Jadeja', 'Suryakumar Yadav', 'Rishabh Pant', 'Shubman Gill',
                     'Yuzvendra Chahal', 'Mohammed Siraj', 'Shreyas Iyer', 'Ishan Kishan', 'Ruturaj Gaikwad',
                     'Faf du Plessis', 'Glenn Maxwell', 'David Warner', 'Jos Buttler', 'Rashid Khan',
                     'Trent Boult', 'Pat Cummins', 'Devon Conway', 'Sanju Samson', 'Axar Patel',
                     'Kuldeep Yadav', 'Shikhar Dhawan', 'Prithvi Shaw', 'Rinku Singh', 'Yashasvi Jaiswal'],

    'player_age':   [35, 36, 42, 30, 31,
                     30, 35, 33, 26, 24,
                     33, 30, 29, 25, 27,
                     np.nan, 35, 37, 33, np.nan,
                     34, 31, 32, 29, np.nan,
                     29, np.nan, 24, 27, 22],

    'player_role':  ['Batsman', 'Batsman', 'Wicketkeeper', 'Bowler', 'Batsman',
                     'Allrounder', 'Allrounder', 'Batsman', 'Wicketkeeper', 'Batsman',
                     'Bowler', 'Bowler', 'Batsman', 'Wicketkeeper', 'Batsman',
                     'Batsman', 'Allrounder', 'Batsman', 'Wicketkeeper', 'Bowler',
                     'Bowler', 'Bowler', 'Batsman', 'Wicketkeeper', 'Allrounder',
                     'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Batsman'],

    'team':         ['RCB', 'MI', 'CSK', 'MI', 'LSG',
                     'GT', 'CSK', 'MI', 'DC', np.nan,
                     'RR', 'RCB', np.nan, 'MI', 'CSK',
                     'RCB', 'RCB', np.nan, 'RR', 'GT',
                     np.nan, 'SRH', 'CSK', 'RR', 'DC',
                     'DC', 'PBKS', np.nan, 'KKR', 'RR'],

    'venue':        ['Chinnaswamy', 'Wankhede', 'Chepauk', 'Wankhede', 'Lucknow',
                     'Ahmedabad', 'Chepauk', 'Wankhede', 'Kotla', 'Ahmedabad',
                     'Jaipur', 'Chinnaswamy', 'Eden Gardens', 'Wankhede', 'Chepauk',
                     'Chinnaswamy', 'Chinnaswamy', 'Hyderabad', 'Jaipur', 'Ahmedabad',
                     'Wankhede', 'Hyderabad', 'Chepauk', 'Jaipur', 'Kotla',
                     'Kotla', 'Mohali', 'Wankhede', 'Eden Gardens', 'Jaipur'],

    'runs_scored':  [82, 56, 45, 5, 91,
                     67, 38, 103, 78, np.nan,
                     2, 8, np.nan, 48, 62,
                     44, 73, 52, 89, 12,
                     0, 15, np.nan, 55, 31,
                     7, 42, np.nan, 48, 78],

    'wickets_taken': [0, 0, 0, 3, 0,
                      2, 1, 0, 0, 0,
                      4, np.nan, 0, 0, 0,
                      0, 1, 0, 0, np.nan,
                      2, 3, 0, 0, np.nan,
                      2, 0, 0, 0, 0],

    'strike_rate':  [145.5, 132.8, 128.4, 50.0, 158.6,
                     175.2, 110.5, 195.3, 162.1, np.nan,
                     40.0, np.nan, np.nan, 135.2, 143.7,
                     122.4, 185.6, 142.1, 168.9, 85.7,
                     0.0, 75.0, np.nan, 148.3, 120.5,
                     58.3, 124.7, np.nan, 160.0, 172.4]
}

df = pd.DataFrame(data)

# Save to CSV
df.to_csv('ipl_match_data.csv', index=False)
print("✅ IPL Match Data CSV created and saved as 'ipl_match_data.csv'")
print(f"\nShape: {df.shape[0]} rows × {df.shape[1]} columns")

✅ IPL Match Data CSV created and saved as 'ipl_match_data.csv'

Shape: 30 rows × 9 columns

In [2]:
# Load the CSV back into a DataFrame
df = pd.read_csv('ipl_match_data.csv')

print("LOADED IPL MATCH DATA")
print("=" * 50)
df

LOADED IPL MATCH DATA
==================================================

,match_id,player_name,player_age,player_role,team,venue,runs_scored,wickets_taken,strike_rate
0,1,Virat Kohli,35.0,Batsman,RCB,Chinnaswamy,82.0,0.0,145.5
1,2,Rohit Sharma,36.0,Batsman,MI,Wankhede,56.0,0.0,132.8
2,3,MS Dhoni,42.0,Wicketkeeper,CSK,Chepauk,45.0,0.0,128.4
3,4,Jasprit Bumrah,30.0,Bowler,MI,Wankhede,5.0,3.0,50.0
4,5,KL Rahul,31.0,Batsman,LSG,Lucknow,91.0,0.0,158.6
5,6,Hardik Pandya,30.0,Allrounder,GT,Ahmedabad,67.0,2.0,175.2
6,7,Ravindra Jadeja,35.0,Allrounder,CSK,Chepauk,38.0,1.0,110.5
7,8,Suryakumar Yadav,33.0,Batsman,MI,Wankhede,103.0,0.0,195.3
8,9,Rishabh Pant,26.0,Wicketkeeper,DC,Kotla,78.0,0.0,162.1
9,10,Shubman Gill,24.0,Batsman,NaN,Ahmedabad,NaN,0.0,NaN
10,11,Yuzvendra Chahal,33.0,Bowler,RR,Jaipur,2.0,4.0,40.0
11,12,Mohammed Siraj,30.0,Bowler,RCB,Chinnaswamy,8.0,NaN,NaN
12,13,Shreyas Iyer,29.0,Batsman,NaN,Eden Gardens,NaN,0.0,NaN
13,14,Ishan Kishan,25.0,Wicketkeeper,MI,Wankhede,48.0,0.0,135.2
14,15,Ruturaj Gaikwad,27.0,Batsman,CSK,Chepauk,62.0,0.0,143.7
15,16,Faf du Plessis,NaN,Batsman,RCB,Chinnaswamy,44.0,0.0,122.4
16,17,Glenn Maxwell,35.0,Allrounder,RCB,Chinnaswamy,73.0,1.0,185.6
17,18,David Warner,37.0,Batsman,NaN,Hyderabad,52.0,0.0,142.1
18,19,Jos Buttler,33.0,Wicketkeeper,RR,Jaipur,89.0,0.0,168.9
19,20,Rashid Khan,NaN,Bowler,GT,Ahmedabad,12.0,NaN,85.7
20,21,Trent Boult,34.0,Bowler,NaN,Wankhede,0.0,2.0,0.0
21,22,Pat Cummins,31.0,Bowler,SRH,Hyderabad,15.0,3.0,75.0
22,23,Devon Conway,32.0,Batsman,CSK,Chepauk,NaN,0.0,NaN
23,24,Sanju Samson,29.0,Wicketkeeper,RR,Jaipur,55.0,0.0,148.3
24,25,Axar Patel,NaN,Allrounder,DC,Kotla,31.0,NaN,120.5
25,26,Kuldeep Yadav,29.0,Bowler,DC,Kotla,7.0,2.0,58.3
26,27,Shikhar Dhawan,NaN,Batsman,PBKS,Mohali,42.0,0.0,124.7
27,28,Prithvi Shaw,24.0,Batsman,NaN,Wankhede,NaN,0.0,NaN
28,29,Rinku Singh,27.0,Batsman,KKR,Eden Gardens,48.0,0.0,160.0
29,30,Yashasvi Jaiswal,22.0,Batsman,RR,Jaipur,78.0,0.0,172.4

In [3]:
# Print number of missing values in each column
print("MISSING VALUES IN EACH COLUMN")
print("=" * 40)
missing = df.isnull().sum()
print(missing)
print(f"\nTotal missing values: {missing.sum()}")
print(f"\nColumns with missing values:")
for col in missing[missing > 0].index:
    print(f"  • {col:<18s} → {missing[col]} missing ({missing[col]/len(df)*100:.1f}%)")

MISSING VALUES IN EACH COLUMN
========================================
match_id         0
player_name      0
player_age       4
player_role      0
team             5
venue            0
runs_scored      4
wickets_taken    3
strike_rate      5
dtype: int64

Total missing values: 21

Columns with missing values:
  • player_age         → 4 missing (13.3%)
  • team               → 5 missing (16.7%)
  • runs_scored        → 4 missing (13.3%)
  • wickets_taken      → 3 missing (10.0%)
  • strike_rate        → 5 missing (16.7%)

### Observation
- The dataset has **30 rows** and **8 columns**.
- Missing values are found in: `player_age`, `team`, `runs_scored`, `wickets_taken`, and `strike_rate`.
- We will handle these missing values in the next questions.

---
## Question 2
**For the 'player_age' column in your IPL dataset, fill all missing values with the median age using pandas' `fillna()` method and display the updated column.**

In [4]:
# Check missing values in 'player_age' BEFORE filling
print("BEFORE fillna()")
print("=" * 45)
print(f"Missing values in 'player_age': {df['player_age'].isnull().sum()}")
print(f"Median age: {df['player_age'].median()}")
print()

# Show the rows that have missing player_age
print("Rows with missing player_age:")
print(df[df['player_age'].isnull()][['player_name', 'player_age', 'team']])
print()

BEFORE fillna()
=============================================
Missing values in 'player_age': 4
Median age: 30.5

Rows with missing player_age:
       player_name  player_age  team
15  Faf du Plessis         NaN   RCB
19     Rashid Khan         NaN    GT
24      Axar Patel         NaN    DC
26  Shikhar Dhawan         NaN  PBKS

In [5]:
# Fill missing values with MEDIAN age
median_age = df['player_age'].median()
df['player_age'] = df['player_age'].fillna(median_age)

# Display the updated column
print("AFTER fillna(median)")
print("=" * 45)
print(f"Missing values in 'player_age': {df['player_age'].isnull().sum()}")
print(f"Median used for filling: {median_age}")
print(f"\nUpdated 'player_age' column:")
print(df[['player_name', 'player_age']].to_string(index=True))

AFTER fillna(median)
=============================================
Missing values in 'player_age': 0
Median used for filling: 30.5

Updated 'player_age' column:
         player_name  player_age
0        Virat Kohli        35.0
1       Rohit Sharma        36.0
2           MS Dhoni        42.0
3     Jasprit Bumrah        30.0
4           KL Rahul        31.0
5      Hardik Pandya        30.0
6    Ravindra Jadeja        35.0
7   Suryakumar Yadav        33.0
8       Rishabh Pant        26.0
9       Shubman Gill        24.0
10  Yuzvendra Chahal        33.0
11    Mohammed Siraj        30.0
12      Shreyas Iyer        29.0
13      Ishan Kishan        25.0
14   Ruturaj Gaikwad        27.0
15    Faf du Plessis        30.5
16     Glenn Maxwell        35.0
17      David Warner        37.0
18       Jos Buttler        33.0
19       Rashid Khan        30.5
20       Trent Boult        34.0
21       Pat Cummins        31.0
22      Devon Conway        32.0
23      Sanju Samson        29.0
24        Axar Patel        30.5
25     Kuldeep Yadav        29.0
26    Shikhar Dhawan        30.5
27      Prithvi Shaw        24.0
28       Rinku Singh        27.0
29  Yashasvi Jaiswal        22.0

### Why use Median?
- **Median** is preferred over mean for filling missing values because it is **not affected by outliers**.
- For example, if one player's age were incorrectly entered as 99, the mean would be skewed, but the median would remain stable.

---
## Question 3
**Suppose the 'team' column in your IPL dataset contains missing values. Replace all missing team names with the constant value 'Unknown' and print the first 10 rows.**

In [6]:
# Check missing values in 'team' BEFORE filling
print("BEFORE fillna()")
print("=" * 45)
print(f"Missing values in 'team': {df['team'].isnull().sum()}")
print("\nRows with missing team:")
print(df[df['team'].isnull()][['player_name', 'team']])
print()

BEFORE fillna()
=============================================
Missing values in 'team': 5

Rows with missing team:
     player_name team
9   Shubman Gill  NaN
12  Shreyas Iyer  NaN
17  David Warner  NaN
20   Trent Boult  NaN
27  Prithvi Shaw  NaN

In [7]:
# Replace missing team names with 'Unknown'
df['team'] = df['team'].fillna('Unknown')

# Print the first 10 rows
print("AFTER fillna('Unknown') — First 10 Rows")
print("=" * 55)
print(f"Missing values in 'team': {df['team'].isnull().sum()}")
print()
print(df[['player_name', 'team']].head(10).to_string(index=True))

AFTER fillna('Unknown') — First 10 Rows
=======================================================
Missing values in 'team': 0

        player_name     team
0       Virat Kohli      RCB
1      Rohit Sharma       MI
2          MS Dhoni      CSK
3    Jasprit Bumrah       MI
4          KL Rahul      LSG
5     Hardik Pandya       GT
6   Ravindra Jadeja      CSK
7  Suryakumar Yadav       MI
8      Rishabh Pant       DC
9      Shubman Gill  Unknown

In [8]:
# Verify: Show all rows that were filled with 'Unknown'
print("\nAll rows where team = 'Unknown':")
print(df[df['team'] == 'Unknown'][['player_name', 'team']].to_string(index=True))

All rows where team = 'Unknown':
     player_name     team
9   Shubman Gill  Unknown
12  Shreyas Iyer  Unknown
17  David Warner  Unknown
20   Trent Boult  Unknown
27  Prithvi Shaw  Unknown

### Why use a constant value?
- For **categorical columns** (like team names), we cannot use mean or median.
- Using a constant like `'Unknown'` preserves the data without introducing false information.
- Alternatively, we could use the **mode** (most frequent team), but that could introduce bias.

---
## Question 4
**Take the 'venue' column (categorical) from your IPL dataset and apply one-hot encoding using pandas' `get_dummies()`. Show the resulting DataFrame with the new columns.**

In [9]:
# BEFORE encoding — show the venue column
print("BEFORE One-Hot Encoding")
print("=" * 40)
print(f"Unique venues: {df['venue'].nunique()}")
print(f"\nVenue values:")
print(df['venue'].value_counts())

BEFORE One-Hot Encoding
========================================
Unique venues: 10

Venue values:
venue
Wankhede        6
Chinnaswamy     4
Chepauk         4
Jaipur          4
Ahmedabad       3
Kotla           3
Eden Gardens    2
Hyderabad       2
Lucknow         1
Mohali          1
Name: count, dtype: int64

In [10]:
# Apply One-Hot Encoding using get_dummies()
df_encoded = pd.get_dummies(df, columns=['venue'], prefix='venue')

# Show the new columns created
venue_cols = [col for col in df_encoded.columns if col.startswith('venue_')]

print("AFTER One-Hot Encoding")
print("=" * 50)
print(f"Original columns: {len(df.columns)}")
print(f"New columns after encoding: {len(df_encoded.columns)}")
print(f"\nNew venue columns created ({len(venue_cols)}):")
for i, col in enumerate(venue_cols, 1):
    print(f"  {i}. {col}")

AFTER One-Hot Encoding
==================================================
Original columns: 9
New columns after encoding: 18

New venue columns created (10):
  1. venue_Ahmedabad
  2. venue_Chepauk
  3. venue_Chinnaswamy
  4. venue_Eden Gardens
  5. venue_Hyderabad
  6. venue_Jaipur
  7. venue_Kotla
  8. venue_Lucknow
  9. venue_Mohali
  10. venue_Wankhede

In [11]:
# Display the resulting DataFrame (player_name + venue columns)
print("\nOne-Hot Encoded Venue Columns (first 10 rows):")
print("=" * 80)
display_cols = ['player_name'] + venue_cols
df_encoded[display_cols].head(10)

One-Hot Encoded Venue Columns (first 10 rows):
================================================================================

,player_name,venue_Ahmedabad,venue_Chepauk,venue_Chinnaswamy,venue_Eden Gardens,venue_Hyderabad,venue_Jaipur,venue_Kotla,venue_Lucknow,venue_Mohali,venue_Wankhede
0,Virat Kohli,False,False,True,False,False,False,False,False,False,False
1,Rohit Sharma,False,False,False,False,False,False,False,False,False,True
2,MS Dhoni,False,True,False,False,False,False,False,False,False,False
3,Jasprit Bumrah,False,False,False,False,False,False,False,False,False,True
4,KL Rahul,False,False,False,False,False,False,False,True,False,False
5,Hardik Pandya,True,False,False,False,False,False,False,False,False,False
6,Ravindra Jadeja,False,True,False,False,False,False,False,False,False,False
7,Suryakumar Yadav,False,False,False,False,False,False,False,False,False,True
8,Rishabh Pant,False,False,False,False,False,False,True,False,False,False
9,Shubman Gill,True,False,False,False,False,False,False,False,False,False

### How One-Hot Encoding Works

| Original `venue` | venue_Ahmedabad | venue_Chepauk | venue_Chinnaswamy | venue_Wankhede | ... |
|-------------------|:-:|:-:|:-:|:-:|:-:|
| Chinnaswamy | 0 | 0 | **1** | 0 | 0 |
| Wankhede | 0 | 0 | 0 | **1** | 0 |
| Chepauk | 0 | **1** | 0 | 0 | 0 |

- Each unique venue becomes a **new binary column** (0 or 1).
- Exactly **one column is 1** per row (the venue for that match).
- This allows ML models to work with categorical data that has **no ordinal relationship** (no venue is "greater" than another).

---
## Question 5
**Use `LabelEncoder` from sklearn to encode the 'player_role' column (e.g., Batsman, Bowler, Allrounder) in your IPL dataset, and display the mapping from original roles to encoded values.**

*Hint: Use LabelEncoder's `classes_` attribute to see the mapping.*

In [12]:
# BEFORE encoding
print("BEFORE Label Encoding")
print("=" * 40)
print(f"Unique roles: {df['player_role'].nunique()}")
print(f"\nRole distribution:")
print(df['player_role'].value_counts())

BEFORE Label Encoding
========================================
Unique roles: 4

Role distribution:
player_role
Batsman         14
Bowler           7
Wicketkeeper     5
Allrounder       4
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Fit and transform the 'player_role' column
df['player_role_encoded'] = le.fit_transform(df['player_role'])

# Display the mapping using classes_ attribute
print("LABEL ENCODING MAPPING")
print("=" * 40)
print(f"\nMapping (classes_ attribute):")
for encoded_val, original_label in enumerate(le.classes_):
    print(f"  {original_label:<18s} → {encoded_val}")

print(f"\n{'='*60}")
print("Player Role — Before vs After Encoding")
print(f"{'='*60}")
print(df[['player_name', 'player_role', 'player_role_encoded']].to_string(index=True))

LABEL ENCODING MAPPING
========================================

Mapping (classes_ attribute):
  Allrounder         → 0
  Batsman            → 1
  Bowler             → 2
  Wicketkeeper       → 3

============================================================
Player Role — Before vs After Encoding
============================================================
         player_name   player_role  player_role_encoded
0        Virat Kohli       Batsman                    1
1       Rohit Sharma       Batsman                    1
2           MS Dhoni  Wicketkeeper                    3
3     Jasprit Bumrah        Bowler                    2
4           KL Rahul       Batsman                    1
5      Hardik Pandya    Allrounder                    0
6    Ravindra Jadeja    Allrounder                    0
7   Suryakumar Yadav       Batsman                    1
8       Rishabh Pant  Wicketkeeper                    3
9       Shubman Gill       Batsman                    1
10  Yuzvendra Chahal        Bowler                    2
11    Mohammed Siraj        Bowler                    2
12      Shreyas Iyer       Batsman                    1
13      Ishan Kishan  Wicketkeeper                    3
14   Ruturaj Gaikwad       Batsman                    1
15    Faf du Plessis       Batsman                    1
16     Glenn Maxwell    Allrounder                    0
17      David Warner       Batsman                    1
18       Jos Buttler  Wicketkeeper                    3
19       Rashid Khan        Bowler                    2
20       Trent Boult        Bowler                    2
21       Pat Cummins        Bowler                    2
22      Devon Conway       Batsman                    1
23      Sanju Samson  Wicketkeeper                    3
24        Axar Patel    Allrounder                    0
25     Kuldeep Yadav        Bowler                    2
26    Shikhar Dhawan       Batsman                    1
27      Prithvi Shaw       Batsman                    1
28       Rinku Singh       Batsman                    1
29  Yashasvi Jaiswal       Batsman                    1

### Label Encoding vs One-Hot Encoding — When to Use Which?

| Method | When to Use | Example |
|--------|------------|----------|
| **Label Encoding** | When categories have an **ordinal (ranked) relationship** | Low → 0, Medium → 1, High → 2 |
| **One-Hot Encoding** | When categories have **no ordinal relationship** | Batsman, Bowler, Allrounder (no ranking) |

### ⚠️ Caution
- Label Encoding assigns numbers like 0, 1, 2, 3 — some ML models may incorrectly interpret this as **Allrounder (0) < Batsman (1) < Bowler (2)**, which has no real meaning.
- For **non-ordinal** categorical data, **One-Hot Encoding** is generally safer.
- However, **tree-based models** (Decision Trees, Random Forest, XGBoost) can handle Label Encoding well.